[theme]
primaryColor = "#E7343F"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#ffffff"
textColor = "#00356B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
